
POST http://localhost:5000/signup
Content-type: application/json

{
  "email": "u1@host.lo",
  "password": "123456"
}
###

POST http://localhost:5000/login
Content-type: application/json

{
  "email": "u1@host.lo",
  "password": "123456"
}
###

GET http://localhost:5000/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMGI2YjcwZDExMDIzY2ZkYTdjOGQ2ZCIsImVtYWlsIjoidTFAaG9zdC5sbyIsImlhdCI6MTY2NTMzNzUyNSwiZXhwIjoxNjY1NDIzOTI1fQ.jspH37kK4bk_acBYMFaMX9Fpvuxg_kB0723rf91PvFA
###

GET http://localhost:5000/
###
