
POST http://localhost:5000/signup
Content-type: application/json

{
  "email": "u1@host.lo",
  "password": "123456"
}
###

POST http://localhost:5000/login
Content-type: application/json

{
  "email": "u1@host.lo",
  "password": "123456"
}
###

GET http://localhost:5000/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNDg0NjAxZDNkNmViMDU0YTM4MjEzMSIsImVtYWlsIjoidTFAaG9zdC5sbyIsImlhdCI6MTY2NTgxOTE2OCwiZXhwIjoxNjY1OTA1NTY4fQ.vn4egtLyApNdCbb3Ffd7jlPjuZBpL9KD6MUcRgTK1yI
###

GET http://localhost:5000/
###
